version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - default
  redis:
    image: redis:7.0-alpine
    networks:
      - default

  api:
    image: bossabox_api
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - '3000:3000'

networks:
  default:
    driver: bridge
